<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
<style type="text/css">
#container {
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
#Header {
	height: 100px;
	width: 800px;
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}
#Header {
	height: 100px;
	width: 800px;
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}
#Navbar {
	height: 50px;
	width: 800px;
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}


#Main content {
	height: auto;
	width: 800px;
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}
#main {
	height: auto;
	width: 800px;
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}
#Footer {
	height: 100px;
	width: 800px;
	margin-right: auto;
	margin-left: auto;
	border-width: 0px;
	border-style: solid;
}
</style>
</head>

<body>
<div id="container">
  <div id="Header"></div>
  <div id="Navbar"></div>
  <div id="main">Content for  id "main" Goes Here</div>
  <div id="Footer">Content for  id "Footer" Goes Here</div>
</div>
</body>
</html>